apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-dump-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/swaartWareZakes/mongo-dump-deploy
    targetRevision: HEAD
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: mongo-dump
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true